---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-backend
spec:
  workspaces:
    - name: shared-workspace
      description: |
        This workspace will receive the cloned git repo and be passed
        to the next Task.
  params:
    - name: git-url
      type: string
      default: "https://github.com/nmajorov/expenses-backend-quarkus.git"
    - name: git-revision
      type: string
      default: "master"
  resources:
    - name: backend-image
      type: image
  tasks:
    - name: deploy-test-containers
      taskRef:
        name: deploy-test-containers
      runAfter:
        - fetch-repository 
      workspaces:
        - name: input
          workspace: shared-workspace
    - name: clean-workspace
      taskRef:
        name: clean-up-backend
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - clean-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: test
      taskRef:
        name: backend-mvn
      runAfter:
        - deploy-test-containers
      workspaces:
        - name: input
          workspace: shared-workspace

    - name: build-quarkus-native
      taskRef:
        name: s2i-quarkus-maven
      runAfter:
        - test
      resources:
        outputs:
          - name: image
            resource: backend-image
      workspaces:
        - name: input
          workspace: shared-workspace

    - name: deploy-quarkus-native
      taskRef:
        name:  deploy-native-backend
      runAfter:
          - build-quarkus-native
      workspaces:
        - name: input
          workspace: shared-workspace

