---
apiVersion: build.rhone.io/v2
language: java
interpreter-version: 3-jdk-11
name: expences-backend-quarkus
version: 1.0-SNAPSHOT
env:
  - POSTGRESQL_SERVICE_NAME={{ rhone_server_hostname }}
  - POSTGRESQL_USER=keycloak
  - POSTGRESQL_PASSWORD=keycloak
  - POSTGRESQL_DATABASE=root
  
  - KEYCLOAK_URL=http://{{rhone_server_hostname}}:7080/auth/realms/basic 
  - KEYCLOAK_INTROSPECT_URL=http://{{rhone_server_hostname}}:7080/auth/realms/basic/protocol/openid-connect/token/introspect
  - KEYCLOAK_CLIENT_ID="backend"
  - KEYCLOAK_SECRET="16c3384b-725d-410d-8107-df3319165f70"

build_podman_params:
    - --add-host "{{ rhone_server_hostname }}:{{rhone_server_ip}}"

scripts:
  pre_install:
    - ./podman/run-full-pod.sh
  post_install:
    - ./podman/delete-pod.sh
