---
#  tasks for openshift4
# ------------------------------------------------------------------------------
# Configure sso
# ------------------------------------------------------------------------------



- debug:
    msg: " Kube config path: {{ kubeconfig }}"


- fail: msg="The variable 'kubeconfig' is not defined"
  when: kubeconfig is undefined



- import_tasks: sso-operator.yaml
  tags:
    - sso

